# Use the official Dart image.
FROM dart:stable AS build

# Resolve app dependencies.
WORKDIR /app
COPY . .
RUN dart pub get

# Build the Flutter web app.
RUN flutter build web --release

# Use a lightweight web server to serve the app.
FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
