name: do_or_pay_web_landing
description: 'Complete your goals for the day or pay from your crypto wallet - landing web page'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_svg: ^1.1.6
  firebase_core: ^2.32.0
  in_app_purchase: ^3.2.0
  cloud_firestore: ^4.17.5
  gif: ^2.3.0
  lottie: ^2.5.0
  firebase_analytics: ^10.10.7
  firebase_analytics_web: ^0.5.7+7
  url_launcher: ^6.3.0
  build_web_compilers: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato-Regular
      fonts:
        - asset:
            assets/fonts/Lato-Regular.ttf
    - family: AppIcons
      fonts:
        - asset:
            assets/fonts/AppIcons.ttf